### ISSUE TITLE
Best place for GtkSharp discussion, questions, tips & informal documentation?

### ISSUE THREAD

**Issue by awittaker** [GtkSharp/GtkSharp#130]
I'm new to Gtk as well as GtkSharp, so I spend a lot of time at the official [Gtk+ 3 Reference](https://developer.gnome.org/gtk3/stable/) figuring out the design & widget choice, and then figuring out the GtkSharp equivalent using my IDE auto-completion and/or browsing the GtkSharp source.

I would like to share my noob findings with other Gtk/GtkSharp noobs (and for my own future reference!), as well as get feedback, ask questions etc.

Historically I've done this type of thing on a BBS style web forum or blog, but I am not sure where to look for GtkSharp?

StackOverflow is good for detailed, well constructed questions, but less so for sharing knowledge.

The GtkSharp Samples project and possibly the GtkSharp GitHub wiki might be good for sharing some types of knowledge - but only once it's discussed, distilled and polished.

Raising GitHub issues for questions (like this one!) & discussion seems inappropriate to me - distracts from tracking real bugs, enhancements etc. 

This issue is partly related to:
 #66 Tutorial?
#124 Can't seem to find the GTK C# documentation anywhere

**Comment by pedrohex** [comment]
Hi and Welcome awittaker,

I’ve been a little off at the moment but my guess is the best place to discuss about this matter is using Gitter at the #GtkSharp channel.

Regards



On 30 Jan 2020, at 18:28, awittaker <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm new to Gtk as well as GtkSharp, so I spend a lot of time at the official Gtk+ 3 Reference<https://developer.gnome.org/gtk3/stable/> figuring out the design & widget choice, and then figuring out the GtkSharp equivalent using my IDE auto-completion and/or browsing the GtkSharp source.

I would like to share my noob findings with other Gtk/GtkSharp noobs (and for my own future reference!), as well as get feedback, ask questions etc.

Historically I've done this type of thing on a BBS style web forum or blog, but I am not sure where to look for GtkSharp?

StackOverflow is good for detailed, well constructed questions, but less so for sharing knowledge.

The GtkSharp Samples project and possibly the GtkSharp GitHub wiki might be good for sharing some types of knowledge - but only once it's discussed, distilled and polished.

Raising GitHub issues for questions (like this one!) & discussion seems inappropriate to me - distracts from tracking real bugs, enhancements etc.

This issue is partly related to:
#66<https://github.com/GtkSharp/GtkSharp/issues/66> Tutorial?
#124<https://github.com/GtkSharp/GtkSharp/issues/124> Can't seem to find the GTK C# documentation anywhere

**Comment by awittaker** [comment]
Thanks Pedro.
Will comment here on the outcome.
