### ISSUE TITLE
StyleContext.GetProperty(string property, StateFlags state) is BROKEN

### ISSUE THREAD

**Issue by LilPoppy** [GtkSharp/GtkSharp#285]
I think the error is from gtk_style_context_get_property.

**Comment by arcusmaximus** [comment]
Perhaps related, I get the impression that IStyleProvider.GetStyleProperty() has the wrong declaration in that the `value` parameter should probably be either `ref` or `out` in order to be usable. It would be even better if this were a return value instead, as is the case with StyleContext.GetProperty() and StyleContext.GetStyleProperty(). Another improvement could be changing the type of the "pspec" parameter from IntPtr to ParamSpec.
