### ISSUE TITLE
Pango.Context.Families returns an array of all nulls on mac

### ISSUE THREAD

**Issue by cwensley** [GtkSharp/GtkSharp#33]
Not sure if this is a GTK# issue or GTK+, but makes it hard to do anything regarding fonts on a Mac.

**Comment by pedrohex** [comment]
Hi cwensley, try this:

            var c = CreatePangoContext();

            foreach (var f in c.Families)
                Console.WriteLine("Name is:{0}", f.Name);

regards

**Comment by cra0zy** [comment]
@cwensley Yea, noticed it a couple of days ago: https://github.com/GtkSharp/GtkSharp/pull/30

I will make a new release tomorrow.

**Comment by cwensley** [comment]
@cra0zy this still seems to be borked if `Pango.Context.Families` is called multiple times..  I get this, and the app crashes:

`GLib-GObject:ERROR:gobject.c:3049:toggle_refs_notify: assertion failed: (tstack.n_toggle_refs == 1)`

**Comment by cra0zy** [comment]
Hmmm...

**Comment by cwensley** [comment]
This is on macOS, btw.

**Comment by cra0zy** [comment]
yea, I am able to repro the error...

Take one bug down and two more shall take its place, hail hydra!!!

**Comment by cra0zy** [comment]
So I figured out what I broke... but I still need to figure out how to fix the original problem in a different manner.

**Comment by cra0zy** [comment]
Oh, I know whats broken... FontFamily on Windows is not a GLib.Object (there is a separate WIn32Family object) so the cast turns it to null...

**Comment by cra0zy** [comment]
Okey, I have a very sneaky patch that will get this stuff working... for now...

**Comment by cra0zy** [comment]
@cwensley @pedrohex If one of you has time to check what FontFamily type Mac returns and submit a PR for it, it would be really helpful. 

You can catch it on the following line (just add a breakpoint on `Pango.Context.Families` and go few steps in): https://github.com/GtkSharp/GtkSharp/blob/develop/Source/Libs/GLibSharp/GType.cs#L214

The fix is straightforward, metadata just needs to know what the parent class is: https://github.com/GtkSharp/GtkSharp/pull/35/files

**Comment by cra0zy** [comment]
The new release is cooking.
