### ISSUE TITLE
User-control Equivalent with Builder

### ISSUE THREAD

**Issue by seikosantana** [GtkSharp/GtkSharp#333]
I'm looking for user-control-like functionality with Glade. I've recently found that I can use GtkBin as top level and then could define custom template or custom widgets or composites. Is there a way to build a defined class inside the glade definition and associate it with a C# class? I couldn't find anything that demonstrates the usage of GtkBuilder for that in C#.

Thanks in advance.

**Comment by zii-dmg** [comment]
Templates allows that but PR isn't merged: https://github.com/GtkSharp/GtkSharp/pull/225

**Comment by seikosantana** [comment]
> You can create composite template in Glade, create C# object from that template in code and add C# object to other widget in code.

Does that need that PR's code for that?
Wonder why that PR isn't merged since it passes all tests..

**Comment by zii-dmg** [comment]
Designer signal - there is `Signals` tab in Glade (near General, Packing, Common, etc). In there you can write handler function name and GTK# will try to connect C# function with same name to that signal.

I don't use signals from designer so don't want to research how to fix issue. I connect signals from code.

I don't know why PR isn't merged. I use that code in my private fork and it works. Without it I can't design complex apps because user controls are everywhere and I want to design controls in designer.

**Comment by seikosantana** [comment]
Thanks for the explanations. I'll try building one from that PR.

**Comment by lytico** [comment]
is in branch develop now: https://github.com/GtkSharp/GtkSharp/pull/392
example is here: 
https://github.com/GtkSharp/GtkSharp/blob/develop/Source/Samples/Sections/Widgets/CompositeWidgetSection.cs
https://github.com/GtkSharp/GtkSharp/blob/develop/Source/Samples/Sections/Widgets/CustomWidgets/CompositeWidget.glade
