### ISSUE TITLE
Clarify that the binding is for GTK+ 3

### ISSUE THREAD

**Issue by ddobrev** [GtkSharp/GtkSharp#46]
https://github.com/GLibSharp/GtkSharp which doesn't even have binary packages makes it clear it's for GTK+ 3. This project which seems vastly superior does not clarify it and might thus repel many users.

**Comment by cra0zy** [comment]
GTK is switching the way they are versioning stuff, instead of having a bunch of 3.X versions they will start bumping the major version with each release (GTK 4 should be getting released this fall). As such I feel like saying that these bindings are for GTK 3 doesn't accomplish much considering they will be updated to always target the newest available version (and of course there will still be previous versions of the package up on nuget).
