### ISSUE TITLE
OpenGL & GLArea

### ISSUE THREAD

**Issue by define-private-public** [GtkSharp/GtkSharp#49]
@cra0zy I've been trying to get a GLArea widget to display that famous "Hello Triangle" OpenGL app.  I was looking at the `OpenGL.NET` bindings and saw that you posted in the Issue Tracker, but you also mentioned that you switched to using OpenTK.

How far have you gotten with being able to use OpenGL and this Gtk binding together?

**Comment by cra0zy** [comment]
![screenshot from 2018-08-02 07-21-31](https://user-images.githubusercontent.com/6773302/43563957-b82f22d8-9624-11e8-9f88-5462cfe6827c.png)

I'll release the samples app once its finished.

That being said I was forced to use .NET Framework for `OpenGL.Net` bindings to work. I do hope that the bindings get fixed in the meantime.

**Comment by define-private-public** [comment]
So is using .Net Core w/ OpenGL not an option then?

**Comment by cra0zy** [comment]
Not for now.

**Comment by cra0zy** [comment]
Do note that both OpenTK and OpenGL.Net do not support .NET Core out of the box right now :\

**Comment by define-private-public** [comment]
That's a shame.  The OpenGL.NET bindings do really look nice...

**Comment by define-private-public** [comment]
Hi,  sorry to bump this old ticket, but I'm looking to do something with OpenGL and GtkSharp.  I know you said you would release the sample app once it's finished, but I haven't seen it released yet.

Could you share the code please?
